package com.lanier.rocoguide.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF4E4CCE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE2DFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF0B006B)
val md_theme_light_secondary = Color(0xFF006780)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFB9EAFF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F29)
val md_theme_light_tertiary = Color(0xFF984063)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E3)
val md_theme_light_onTertiaryContainer = Color(0xFF3E001F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF47464F)
val md_theme_light_outline = Color(0xFF777680)
val md_theme_light_inverseOnSurface = Color(0xFFF3EFF4)
val md_theme_light_inverseSurface = Color(0xFF313034)
val md_theme_light_inversePrimary = Color(0xFFC2C1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4E4CCE)

val md_theme_dark_primary = Color(0xFFC2C1FF)
val md_theme_dark_onPrimary = Color(0xFF1A09A1)
val md_theme_dark_primaryContainer = Color(0xFF3530B6)
val md_theme_dark_onPrimaryContainer = Color(0xFFE2DFFF)
val md_theme_dark_secondary = Color(0xFF5ED4FC)
val md_theme_dark_onSecondary = Color(0xFF003544)
val md_theme_dark_secondaryContainer = Color(0xFF004D61)
val md_theme_dark_onSecondaryContainer = Color(0xFFB9EAFF)
val md_theme_dark_tertiary = Color(0xFFFFB0CA)
val md_theme_dark_onTertiary = Color(0xFF5D1134)
val md_theme_dark_tertiaryContainer = Color(0xFF7A294B)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF47464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5D0)
val md_theme_dark_outline = Color(0xFF918F9A)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inversePrimary = Color(0xFF4E4CCE)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC2C1FF)

val local_default_main_background_light = Color(0xFFEDEDED)
val local_default_lazy_item_light = Color(0xFFFEFBFF)
val local_default_racial_value_light = Color(0xFF4E4CCE)
val local_default_power_tv_value_light = Color(0xFF4B9219)
val local_default_attack_tv_value_light = Color(0xFFBE512D)
val local_default_defense_tv_value_light = Color(0xFF199290)
val local_default_magic_attack_tv_value_light = Color(0xFF561992)
val local_default_magic_defense_tv_value_light = Color(0xFF195392)
val local_default_speed_tv_value_light = Color(0xFF928C19)

val local_default_main_background_dark = Color(0xFF111111)
val local_default_lazy_item_dark = Color(0xFF1C1B20)
val local_default_racial_value_dark = Color(0xFFC2C1FF)
val local_default_power_tv_value_dark = Color(0xFF70D827)
val local_default_attack_tv_value_dark = Color(0xFFF0683B)
val local_default_defense_tv_value_dark = Color(0xFF25D2CF)
val local_default_magic_attack_tv_value_dark = Color(0xFF983DF0)
val local_default_magic_defense_tv_value_dark = Color(0xFF257BD8)
val local_default_speed_tv_value_dark = Color(0xFFDED526)
